import { getAppLanguage } from '../i18n';

const vi = {
  tabLabel: 'Cập nhật',
  tabDescription: 'Kiểm tra và cài đặt phiên bản ChatCMD mới.',
  categoryDescription: 'Quản lý phiên bản và cập nhật ứng dụng từ GitHub Releases.',
  introTitle: 'Cập nhật ChatCMD',
  introDescription: 'ChatCMD kiểm tra GitHub Releases và chọn đúng gói cài đặt theo hệ điều hành, kiến trúc máy của bạn.',
  currentVersion: 'Phiên bản hiện tại',
  latestVersion: 'Phiên bản mới',
  release: 'Bản phát hành GitHub',
  platform: 'Nền tảng',
  check: 'Kiểm tra cập nhật',
  checking: 'Đang kiểm tra…',
  update: 'Cập nhật ngay',
  upToDate: 'Bạn đang sử dụng phiên bản mới nhất.',
  noPublishedVersion: 'Hiện chưa có bản phát hành GitHub phù hợp.',
  unavailable: 'Có phiên bản mới nhưng chưa có file cài đặt phù hợp với kiến trúc máy này.',
  releaseNotes: 'Nội dung phiên bản',
  openRelease: 'Mở trên GitHub',
  confirmTitle: 'Xác nhận cập nhật',
  confirmDescription: 'ChatCMD sẽ tải, xác minh, thay thế file ứng dụng rồi tự khởi động lại.',
  confirmWarning: 'Bạn có chắc chắc muốn cập nhật không? Hãy chắc chắn không có đoạn trò chuyện nào đang hoạt động để tránh mất dữ liệu.',
  cancel: 'Hủy',
  confirmUpdate: 'Xác nhận cập nhật',
  downloading: 'Đang tải bản cập nhật từ GitHub',
  verifying: 'Đang xác minh SHA-256',
  extracting: 'Đang giải nén gói cập nhật',
  preparing: 'Đang chuẩn bị cài đặt',
  ready: 'Bản cập nhật đã sẵn sàng',
  readyInstruction: 'Các file đã được tải, xác minh và chuẩn bị xong. ChatCMD sẽ khởi động lại để hoàn tất cài đặt.',
  restart: 'Khởi động lại để hoàn tất',
  restarting: 'Đang đóng và khởi động lại ChatCMD…',
  failed: 'Cập nhật thất bại',
  retry: 'Thử lại',
  unsupported: 'Tự động cập nhật hiện chỉ hỗ trợ Windows và macOS.',
  popupTitle: 'Có bản cập nhật ChatCMD mới',
  popupDescription: 'GitHub Releases có phiên bản mới hơn cho thiết bị này.',
  popupBadge: 'Bản cập nhật mới',
  popupTrust: 'Gói cài đặt được tải trực tiếp từ GitHub Releases và kiểm tra SHA-256 trước khi thay file ứng dụng.',
  goUpdate: 'Tới cập nhật',
  close: 'Đóng',
  downloadStep: 'Tải file',
  verifyStep: 'Xác minh',
  extractStep: 'Giải nén',
  prepareStep: 'Chuẩn bị',
  restartStep: 'Khởi động lại',
  waitingForRestart: 'Đang chờ ChatCMD khởi động lại…',
  updaterReady: 'Sẵn sàng',
  updaterUnavailable: 'Không có gói phù hợp',
  checksumVerified: 'Checksum đã xác minh',
};

const en: typeof vi = {
  tabLabel: 'Update',
  tabDescription: 'Check for and install new ChatCMD versions.',
  categoryDescription: 'Manage app versions and updates from GitHub Releases.',
  introTitle: 'Update ChatCMD',
  introDescription: 'ChatCMD checks GitHub Releases and selects the correct package for your operating system and CPU architecture.',
  currentVersion: 'Current version',
  latestVersion: 'New version',
  release: 'GitHub release',
  platform: 'Platform',
  check: 'Check for updates',
  checking: 'Checking…',
  update: 'Update now',
  upToDate: 'You are using the latest version.',
  noPublishedVersion: 'No suitable GitHub release is currently available.',
  unavailable: 'A newer version exists, but no installer is available for this architecture.',
  releaseNotes: 'Release notes',
  openRelease: 'Open on GitHub',
  confirmTitle: 'Confirm update',
  confirmDescription: 'ChatCMD will download, verify, replace the application files, and then restart automatically.',
  confirmWarning: 'Are you sure you want to update? Make sure no conversation is active to avoid losing data.',
  cancel: 'Cancel',
  confirmUpdate: 'Confirm update',
  downloading: 'Downloading update from GitHub',
  verifying: 'Verifying SHA-256',
  extracting: 'Extracting update package',
  preparing: 'Preparing installation',
  ready: 'Update is ready',
  readyInstruction: 'The files were downloaded, verified, and prepared successfully. ChatCMD will restart to finish installation.',
  restart: 'Restart to finish',
  restarting: 'Closing and restarting ChatCMD…',
  failed: 'Update failed',
  retry: 'Try again',
  unsupported: 'Automatic updates are currently supported only on Windows and macOS.',
  popupTitle: 'A new ChatCMD update is available',
  popupDescription: 'GitHub Releases has a newer version for this device.',
  popupBadge: 'New update',
  popupTrust: 'The package is downloaded directly from GitHub Releases and SHA-256 is verified before application files are replaced.',
  goUpdate: 'Go to update',
  close: 'Close',
  downloadStep: 'Download',
  verifyStep: 'Verify',
  extractStep: 'Extract',
  prepareStep: 'Prepare',
  restartStep: 'Restart',
  waitingForRestart: 'Waiting for ChatCMD to restart…',
  updaterReady: 'Ready',
  updaterUnavailable: 'No suitable package',
  checksumVerified: 'Checksum verified',
};

export type UpdateCopy = typeof vi;

export function updateCopy(): UpdateCopy {
  return getAppLanguage() === 'vi' ? vi : en;
}
