import { getAppLanguage } from '../i18n';

const vi = {
  tabLabel: 'Cập nhật',
  tabDescription: 'Kiểm tra và cài đặt phiên bản ChatCMD mới.',
  categoryDescription: 'Quản lý phiên bản và cập nhật ứng dụng an toàn.',
  introTitle: 'Cập nhật ChatCMD',
  introDescription: 'ChatCMD sẽ kiểm tra đúng gói cài đặt theo hệ điều hành và kiến trúc máy của bạn.',
  currentVersion: 'Phiên bản hiện tại',
  latestVersion: 'Phiên bản mới',
  platform: 'Nền tảng',
  check: 'Kiểm tra cập nhật',
  checking: 'Đang kiểm tra…',
  update: 'Cập nhật',
  upToDate: 'Bạn đang sử dụng phiên bản mới nhất.',
  noPublishedVersion: 'Hiện chưa có phiên bản nào được phát hành cho nền tảng này.',
  unavailable: 'Có phiên bản mới nhưng chưa có file cài đặt phù hợp với kiến trúc máy này.',
  releaseNotes: 'Nội dung cập nhật',
  confirmTitle: 'Xác nhận cập nhật',
  confirmDescription: 'Quá trình cập nhật sẽ tạm thời làm ChatCMD không thể sử dụng.',
  confirmWarning: 'Bạn có chắc chắn muốn cập nhật không? Vui lòng chắc chắn không có đoạn trò chuyện nào đang diễn ra. Bạn sẽ không thể sử dụng ChatCMD trong lúc cập nhật.',
  cancel: 'Hủy',
  confirmUpdate: 'Xác nhận cập nhật',
  downloading: 'Đang tải bản cập nhật',
  extracting: 'Đang giải nén',
  preparing: 'Đang chuẩn bị cài đặt',
  ready: 'Đã chuẩn bị xong bản cập nhật',
  readyInstruction: 'Bản cập nhật đã được tải và giải nén an toàn. Nhấn “Khởi động lại để hoàn tất”; ChatCMD sẽ đóng, thay file ứng dụng và extension, tự mở lại, sau đó trang này sẽ tự tải lại.',
  restart: 'Khởi động lại để hoàn tất',
  restarting: 'Đang khởi động lại ChatCMD…',
  failed: 'Cập nhật thất bại',
  retry: 'Thử lại',
  unsupported: 'Tự động cập nhật hiện chỉ hỗ trợ Windows và macOS.',
  popupTitle: 'Có bản cập nhật ChatCMD mới',
  popupDescription: 'Một phiên bản mới đã sẵn sàng cho thiết bị này.',
  popupBadge: 'Bản cập nhật mới',
  popupTrust: 'ChatCMD sẽ tải đúng gói cập nhật cho thiết bị và chỉ cài đặt sau khi bạn xác nhận.',
  goUpdate: 'Tới cập nhật',
  close: 'Đóng',
  downloadStep: 'Tải file',
  extractStep: 'Giải nén',
  prepareStep: 'Chuẩn bị',
  restartStep: 'Khởi động lại',
  waitingForRestart: 'Đang chờ ChatCMD khởi động lại…',
  manualDownload: 'Nếu không thể cập nhật tự động, xin vui lòng vào https://chatcmd.net/download để tải thủ công về.',
};

const en: typeof vi = {
  tabLabel: 'Update',
  tabDescription: 'Check for and install new ChatCMD versions.',
  categoryDescription: 'Manage app versions and install updates safely.',
  introTitle: 'Update ChatCMD',
  introDescription: 'ChatCMD checks the correct package for your operating system and CPU architecture.',
  currentVersion: 'Current version',
  latestVersion: 'New version',
  platform: 'Platform',
  check: 'Check for updates',
  checking: 'Checking…',
  update: 'Update',
  upToDate: 'You are using the latest version.',
  noPublishedVersion: 'No version has been published for this platform yet.',
  unavailable: 'A newer version exists, but no installer is available for this architecture.',
  releaseNotes: 'Release notes',
  confirmTitle: 'Confirm update',
  confirmDescription: 'ChatCMD will be temporarily unavailable while the update is installed.',
  confirmWarning: 'Are you sure you want to update? Make sure no conversation is currently running. You will not be able to use ChatCMD during the update.',
  cancel: 'Cancel',
  confirmUpdate: 'Confirm update',
  downloading: 'Downloading update',
  extracting: 'Extracting files',
  preparing: 'Preparing installation',
  ready: 'Update is ready',
  readyInstruction: 'The update was downloaded and extracted safely. Click “Restart to finish”; ChatCMD will close, replace the app and extension files, reopen automatically, and this page will reload.',
  restart: 'Restart to finish',
  restarting: 'Restarting ChatCMD…',
  failed: 'Update failed',
  retry: 'Try again',
  unsupported: 'Automatic updates are currently supported only on Windows and macOS.',
  popupTitle: 'A new ChatCMD update is available',
  popupDescription: 'A newer version is ready for this device.',
  popupBadge: 'New update',
  popupTrust: 'ChatCMD will download the correct package for this device and install it only after you confirm.',
  goUpdate: 'Go to update',
  close: 'Close',
  downloadStep: 'Download',
  extractStep: 'Extract',
  prepareStep: 'Prepare',
  restartStep: 'Restart',
  waitingForRestart: 'Waiting for ChatCMD to restart…',
  manualDownload: 'If automatic update is unavailable, please visit https://chatcmd.net/download to download ChatCMD manually.',
};

export type UpdateCopy = typeof vi;

export function updateCopy(): UpdateCopy {
  return getAppLanguage() === 'vi' ? vi : en;
}
