import { Copy, KeyRound, Pencil, Plus, RotateCw, Trash2 } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { api } from '../api';
import { Empty, ErrorState, Loading, Modal, PageHeading, ProblemBanner, StatusBadge } from '../components';
import type { Agent, AgentInput, SecretResult } from '../types';
import { useLoad } from '../useLoad';

const blank: AgentInput = { name: '', enabled: true, projectFolder: '', toolIds: [] };
export function AgentsPage() {
  const agents = useLoad(api.agents, []); const tools = useLoad(api.tools, []); const presets = useLoad(api.presets, []); const [editor, setEditor] = useState<Agent | 'new'>(); const [secret, setSecret] = useState<SecretResult>(); const [problem, setProblem] = useState('');
  const updateList = (next: Agent) => agents.setData((current) => current ? [next, ...current.filter((item) => item.id !== next.id)] : [next]);
  const save = async (input: AgentInput) => { setProblem(''); try { if (editor === 'new') { const created = await api.createAgent(input); if (created.agent) updateList(created.agent); setSecret(created); } else if (editor) updateList(await api.updateAgent(editor.id, input)); setEditor(undefined); } catch (error) { setProblem(error instanceof Error ? error.message : 'Save failed'); } };
  const rotate = async (agent: Agent) => { setProblem(''); try { setSecret(await api.rotateAgentSecret(agent.id)); } catch (error) { setProblem(error instanceof Error ? error.message : 'Rotation failed'); } };
  const remove = async (agent: Agent) => { if (!confirm(`Delete local agent “${agent.name}”?`)) return; try { await api.deleteAgent(agent.id); agents.setData((current) => current?.filter((item) => item.id !== agent.id)); } catch (error) { setProblem(error instanceof Error ? error.message : 'Delete failed'); } };
  return <div><PageHeading eyebrow="MCP ACCESS" title="Agents" body="Local clients, project scope, and tool permissions." actions={<button className="button primary" onClick={() => setEditor('new')}><Plus />New agent</button>} /><ProblemBanner message={problem} clear={() => setProblem('')} />
    {agents.loading ? <Loading label="Loading agents" /> : agents.error ? <ErrorState message={agents.error} retry={() => void agents.reload()} /> : !agents.data?.length ? <Empty title="No MCP agents" body="Create an agent to receive a one-time MCP connection URL." /> : <div className="agent-grid">{agents.data.map((agent) => <article className="agent-card" key={agent.id}><header><span className="agent-avatar"><KeyRound /></span><div><strong>{agent.name}</strong><code>{agent.id}</code></div><StatusBadge state={agent.enabled ? 'ready' : 'stopped'} label={agent.enabled ? 'Enabled' : 'Disabled'} /></header><dl><div><dt>Project folder</dt><dd>{agent.projectFolder || 'All configured roots'}</dd></div><div><dt>Tool access</dt><dd>{agent.toolIds.length} selected{agent.presetId ? ` · preset ${agent.presetId}` : ''}</dd></div><div><dt>Token</dt><dd>{agent.secretLast4 ? `•••• ${agent.secretLast4}` : 'Hidden'}</dd></div></dl><div className="button-row"><button className="button secondary compact" onClick={() => setEditor(agent)}><Pencil />Edit</button><button className="button secondary compact" onClick={() => void rotate(agent)}><RotateCw />Rotate token</button><button className="icon-button danger-icon" aria-label={`Delete ${agent.name}`} onClick={() => void remove(agent)}><Trash2 /></button></div></article>)}</div>}
    {editor && <AgentEditor agent={editor === 'new' ? undefined : editor} tools={tools.data ?? []} presets={presets.data ?? []} close={() => setEditor(undefined)} save={save} />}
    {secret && <SecretModal result={secret} close={() => setSecret(undefined)} />}
  </div>;
}
function AgentEditor({ agent, tools, presets, close, save }: { agent?: Agent; tools: Awaited<ReturnType<typeof api.tools>>; presets: Awaited<ReturnType<typeof api.presets>>; close: () => void; save: (input: AgentInput) => Promise<void> }) {
  const [value, setValue] = useState<AgentInput>(agent ? { name: agent.name, enabled: agent.enabled, projectFolder: agent.projectFolder, presetId: agent.presetId, toolIds: agent.toolIds } : blank); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); await save(value); setBusy(false); };
  return <Modal title={agent ? `Edit ${agent.name}` : 'Create MCP agent'} description="Permissions apply only to this local endpoint." close={close}><form className="form-stack" onSubmit={submit}><label>Name<input required maxLength={100} value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label><label>Project folder<input value={value.projectFolder} onChange={(event) => setValue({ ...value, projectFolder: event.target.value })} placeholder="D:\\Projects\\example" /></label><label>Permission preset<select value={value.presetId ?? ''} onChange={(event) => setValue({ ...value, presetId: event.target.value || undefined })}><option value="">Custom permissions</option>{presets.map((preset) => <option value={preset.id} key={preset.id}>{preset.name}</option>)}</select></label><fieldset><legend>Per-tool permissions</legend><div className="permission-list">{tools.map((tool) => <label className="check-row" key={tool.id}><input type="checkbox" checked={value.toolIds.includes(tool.id)} onChange={(event) => setValue({ ...value, toolIds: event.target.checked ? [...value.toolIds, tool.id] : value.toolIds.filter((id) => id !== tool.id) })} /><span><strong>{tool.name}{tool.dangerous && <em>Dangerous</em>}</strong><small>{tool.description ?? tool.group}</small></span></label>)}</div></fieldset><label className="check-row"><input type="checkbox" checked={value.enabled} onChange={(event) => setValue({ ...value, enabled: event.target.checked })} /><span><strong>Enabled</strong><small>Allow this client to use its tokenized MCP URL.</small></span></label><div className="modal-actions"><button className="button secondary" type="button" onClick={close}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Save agent'}</button></div></form></Modal>;
}
function SecretModal({ result, close }: { result: SecretResult; close: () => void }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(result.endpoint); setCopied(true); }; return <Modal title="Save this MCP URL now" description="Use this URL directly in the MCP client. No Authorization header is required." close={close} dangerous><div className="secret-box"><code>{result.endpoint}</code><button className="button primary" onClick={() => void copy()}><Copy />{copied ? 'Copied' : 'Copy MCP URL'}</button></div><p className="warning-copy">The final path segment is the agent token and is shown only once. Keep the complete URL out of source control, screenshots, browser history, and shared logs.</p><div className="modal-actions"><button className="button secondary" onClick={close}>I saved the MCP URL</button></div></Modal>; }
