import { BookOpen, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { api } from '../api';
import { Empty, ErrorState, Loading, PageHeading, StatusBadge } from '../components';
import type { Skill } from '../types';
import { useLoad } from '../useLoad';

const CONTENT_LIMIT = 50_000;
export function SkillsPage() { const result = useLoad(api.skills, []); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Skill>(); const [problem, setProblem] = useState(''); const filtered = useMemo(() => (result.data ?? []).filter((skill) => `${skill.name} ${skill.source ?? ''} ${skill.description ?? ''}`.toLowerCase().includes(query.toLowerCase())), [query, result.data]);
  const open = async (skill: Skill) => { setProblem(''); try { setSelected(await api.skill(skill.id)); } catch (error) { setProblem(error instanceof Error ? error.message : 'Could not load skill'); } };
  return <div className="split-page"><div><PageHeading eyebrow="INSTRUCTION CATALOG" title="Skills" body="Effective source, precedence, and shadowing on this machine." /><div className="filter-bar"><label className="search-field"><Search /><span className="sr-only">Search skills</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search skills" /></label></div>{problem && <p role="alert" className="field-error">{problem}</p>}{result.loading ? <Loading label="Loading skills" /> : result.error ? <ErrorState message={result.error} retry={() => void result.reload()} /> : !filtered.length ? <Empty title="No skills found" body="Installed local skills appear here." /> : <div className="record-list">{filtered.map((skill) => <button className={`record-row skill-row ${selected?.id === skill.id ? 'selected' : ''}`} onClick={() => void open(skill)} key={skill.id}><span className="record-icon"><BookOpen /></span><div className="record-main"><strong>{skill.name}</strong><code>{skill.source ?? 'Unknown source'}</code><small>Precedence {skill.precedence ?? '—'}{skill.shadowed ? ' · shadowed' : ''}</small></div><div className="record-meta"><StatusBadge state={skill.enabled && !skill.shadowed ? 'ready' : 'stopped'} label={skill.shadowed ? 'Shadowed' : skill.enabled ? 'Enabled' : 'Disabled'} /></div></button>)}</div>}</div><aside className="content-viewer" aria-label="Skill content"><header><span className="eyebrow">CONTENT VIEWER</span><h2>{selected?.name ?? 'Select a skill'}</h2></header>{selected ? <><p>{selected.description}</p><pre>{(selected.content ?? 'No content returned.').slice(0, CONTENT_LIMIT)}{(selected.content?.length ?? 0) > CONTENT_LIMIT ? '\n\n[Content truncated]' : ''}</pre></> : <div className="inline-empty">Choose a skill to inspect bounded content.</div>}</aside></div>; }
