import type { AppLanguage } from '../i18n';

const en = {
  popupMissingTitle: 'ChatGPT extension is not installed',
  popupMissingDescription: 'Install the ChatCMD browser extension to communicate with ChatGPT directly from this UI.',
  popupOutdatedTitle: 'ChatGPT extension needs an update',
  popupOutdatedDescription: 'The connected extension does not match the version required by this ChatCMD build.',
  goSetup: 'Open installation guide',
  close: 'Close',
  pageEyebrow: 'CHATGPT EXTENSION',
  pageTitle: 'Install the ChatGPT extension',
  pageBody: 'ChatCMD ships the unpacked browser extension beside the application so you can load it directly in a Chromium-based browser.',
  connected: 'Extension ready',
  missing: 'Extension not detected',
  outdated: 'Extension version mismatch',
  currentVersion: 'Detected version',
  requiredVersion: 'Required version',
  notDetected: 'Not detected',
  checkAgain: 'Check again',
  checking: 'Checking…',
  quickActions: 'Quick actions',
  openBrowser: 'Open browser extensions',
  openBrowserHint: 'Opens the extensions management page in the detected browser.',
  openFolder: 'Open extension folder',
  openFolderHint: 'Opens the packaged chatgpt-extension folder beside the ChatCMD installation.',
  guideTitle: 'Installation steps',
  step1Title: 'Open the browser extensions page',
  step1Body: 'Use the quick action above, or open chrome://extensions/ in Chrome, edge://extensions/ in Microsoft Edge, or brave://extensions/ in Brave.',
  step2Title: 'Enable Developer mode',
  step2Body: 'Turn on Developer mode in the extensions page so the browser allows loading an unpacked extension.',
  step3Title: 'Load the packaged extension',
  step3Body: 'Choose Load unpacked, then select the chatgpt-extension folder that ships beside ChatCMD.',
  step4Title: 'Reload ChatCMD and verify',
  step4Body: 'Return to ChatCMD, reload the page, then use Check again. ChatCMD currently requires extension version 0.1.13.',
};

type ExtensionCopy = { [K in keyof typeof en]: string };

const vi: ExtensionCopy = {
  popupMissingTitle: 'Bạn chưa cài tiện ích ChatGPT cho ChatCMD',
  popupMissingDescription: 'Cài tiện ích trình duyệt của ChatCMD để giao tiếp với ChatGPT trực tiếp ngay trên UI này.',
  popupOutdatedTitle: 'Tiện ích ChatGPT cần được cập nhật',
  popupOutdatedDescription: 'Phiên bản tiện ích đang kết nối không khớp với phiên bản mà bản ChatCMD này yêu cầu.',
  goSetup: 'Mở hướng dẫn cài đặt',
  close: 'Đóng',
  pageEyebrow: 'TIỆN ÍCH CHATGPT',
  pageTitle: 'Cài đặt tiện ích ChatGPT',
  pageBody: 'ChatCMD đính kèm sẵn extension dạng unpacked bên cạnh ứng dụng để bạn có thể nạp trực tiếp vào trình duyệt Chromium.',
  connected: 'Tiện ích đã sẵn sàng',
  missing: 'Chưa phát hiện tiện ích',
  outdated: 'Sai phiên bản tiện ích',
  currentVersion: 'Phiên bản phát hiện được',
  requiredVersion: 'Phiên bản yêu cầu',
  notDetected: 'Chưa phát hiện',
  checkAgain: 'Kiểm tra lại',
  checking: 'Đang kiểm tra…',
  quickActions: 'Thao tác nhanh',
  openBrowser: 'Mở trang tiện ích trình duyệt',
  openBrowserHint: 'Mở nhanh trang quản lý extension của trình duyệt đang được nhận diện.',
  openFolder: 'Mở thư mục extension',
  openFolderHint: 'Mở thư mục chatgpt-extension được đóng gói cạnh bản cài ChatCMD.',
  guideTitle: 'Các bước cài đặt',
  step1Title: 'Mở trang quản lý extension',
  step1Body: 'Dùng nút thao tác nhanh ở trên, hoặc mở chrome://extensions/ trên Chrome, edge://extensions/ trên Microsoft Edge hay brave://extensions/ trên Brave.',
  step2Title: 'Bật Developer mode',
  step2Body: 'Bật Developer mode trong trang extension để trình duyệt cho phép nạp extension dạng unpacked.',
  step3Title: 'Nạp extension đi kèm ChatCMD',
  step3Body: 'Chọn Load unpacked, sau đó chọn thư mục chatgpt-extension nằm cạnh bản cài ChatCMD.',
  step4Title: 'Reload ChatCMD và kiểm tra',
  step4Body: 'Quay lại ChatCMD, reload trang rồi bấm Kiểm tra lại. ChatCMD hiện yêu cầu extension phiên bản 0.1.13.',
};

export function extensionCopy(language: AppLanguage) {
  return language === 'vi' ? vi : en;
}
